semi: false
useTabs: false
tabWidth: 2
printWidth: 100
singleQuote: true
trailingComma: es5
bracketSpacing: true
jsxSingleQuote: true
jsxBracketSameLine: false
arrowParens: avoid
quoteProps: as-needed
endOfLine: lf
