packages:
  - .
  - docs
catalog:
  '@vuepress/bundler-vite': ^2.0.0-rc.22
  '@vuepress/helper': ^2.0.0-rc.99
  '@vuepress/plugin-shiki': ^2.0.0-rc.99
  '@vuepress/theme-default': ^2.0.0-rc.101
  vuepress: ^2.0.0-rc.22
