# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:latest

jobs:
  #------------------------------------------------------------
  # 1. Install dependencies
  #------------------------------------------------------------
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  #------------------------------------------------------------
  # 2. Run parallel jobs:
  #   => linter
  #   => test
  #------------------------------------------------------------

  run-linter-check:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Linter
          command: yarn lint

  run-test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Test
          command: yarn test

  #------------------------------------------------------------
  # 3. Build docs
  #------------------------------------------------------------

  build-docs:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Docs
          command: yarn build

#------------------------------------------------------------
# Workflows
#------------------------------------------------------------

workflows:
  version: 2
  build:
    jobs:
      - install-dependencies
      - run-linter-check: { requires: [install-dependencies] }
      - run-test: { requires: [install-dependencies] }
      - build-docs: { requires: [run-linter-check, run-test] }
