name: CI

on:
  pull_request:
    branches:
      - next
  push:
    branches:
      - next

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          node-version: lts/*
      - uses: actions/setup-node@v3
        with:
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run typecheck
      - run: pnpm run build
      - run: pnpm run build:docs
