name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - next
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - uses: pnpm/action-setup@v2
        with:
          run_install: true

      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run build:docs

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist
