name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true
      - run: pnpm run lint
